### PR TITLE
Optimizing the code of square cut a little

### PR DESCRIPTION
**Pull request by Afif13**
Well, I cannot resist finding optimization to reduce my code 😅
Also fixed a tiny typo in the doc.

### CODE REVIEW

**Review by argyleink — APPROVED** [review]
awesome, thank you! <3

**Comment by argyleink** [comment]
i have an announcement tweet scheduled for tomorrow mornin 👍🏻 
thanks for the polish nudges!

**Comment by Afif13** [comment]
Great! hope people will find them useful 😁

**Comment by argyleink** [comment]
I hope it helps drive folks to your generators 🙂

**Pull request merged**
