### PR TITLE
adds inner-shadow-highlight variable to inner shadow 1-4

### PR DESCRIPTION
**Pull request by argyleink**
Screenshot 2023-08-29 at 3 54 26 PM

### CODE REVIEW

**Comment by argyleink** [comment]
tests are failing because I added a new prop

**Comment by ezzatron** [comment]
@argyleink Just a heads up that the inner shadow highlight looks a bit... weird on light themes.

With `--inner-shadow-highlight` it looks kind of like there's a dark 1px border along the top edge of the inset:

Screenshot 2023-10-24 at 20 56 32

Without `--inner-shadow-highlight`:

Screenshot 2023-10-24 at 20 56 21

(Note that this component deliberately only uses the inset shadow on the top and bottom)

As usual, it's easy to override, but I thought I'd bring it up in case it was just an oversight. Cheers!

**Comment by argyleink** [comment]
ewww that's gross agree, lemme fix!

**Comment by argyleink** [comment]
fixed in `v1.6.9` 🙏🏻

**Pull request merged**
