### PR TITLE
Extras `buttons.min.css`

### LINKED ISSUE #152: Normalize should bring decent buttons
it brings a nice summary and details after all, why not align these interactive elements?

### PR DESCRIPTION
**Pull request by argyleink**
fixes #152 
- [x] icons
- [x] custom accents
- [x] custom size
- [x] adaptive (light/dark)
- [x] reduced motion
- [x] supports inputs and buttons, also helps unmarked buttons look like submit buttons
- [x] file input button matches
- [ ] docs

play around with the plain css [prototype here](https://codepen.io/argyleink/pen/KKXYLmy?editors=1100)

### CODE REVIEW

**Comment by argyleink** [comment]
add `--_size` as another top level customization lever

**Comment by argyleink** [comment]
move normalize.css button styles into this file

**Comment by argyleink** [comment]
gonna need docs or some docs built into a demo codepen

**Comment by argyleink** [comment]
2 small firefox issues:
- [ ] icon stroke color
- [ ] accent and link color comment value

**Comment by davideast** [comment]
Amazing.

I think the key thing here will be explaining that:

- Including this extra will bring a very low specificity (by using where)
- You can easily customize it with other props

I started a really simple docs example to showcase some of these thoughts.

https://open-props--button-docs-a6hwptl6.web.app/#buttons

**Comment by davideast** [comment]
Amazing.

I think the key thing here will be explaining that:

- Including this extra will bring a very low specificity (by using where)
- You can easily customize it with other props

I started a really simple docs example to showcase some of these thoughts.

https://open-props--button-docs-a6hwptl6.web.app/#buttons

**Comment by argyleink** [comment]
Screen Shot 2022-01-22 at 9 44 25 PM

seein that def gets me pumped! i bet we could easily build a little experience too that changes the accent color, size and text colors. spit out the tiny bits of mod props needed, they can copy and paste them in their css for some branded looks 🙂 

#### i think we need an Extra section in the bottom nav instead of Buttons tho: 
In extra we can document normalize props and the buttons. v1 def doesnt need to be interactive. my idea up until now was to make a normalize codepen and a buttons codepen, and kinda docublog them there. i really like the idea of an Extras section tho, really going to help clear things up. makes this related to #89 👍🏻

**Comment by argyleink** [comment]
docs to come in a separate PR, this is ready for early access

**Pull request merged**
