### PR TITLE
docs: add autocomplete guidelines for users that use VScode as their primary IDE

### PR DESCRIPTION
**Pull request by Caleb335**
Hi @argyleink,

Kindly review.

### CODE REVIEW

**Review by argyleink — CHANGES_REQUESTED** [review]
ty! the core is pretty much all done 🙂 

a few requests i hope are ok!
- can you slim down the commit to just the vscode section, looks like a linter or formatter ran across the whole file
- remove the package-lock from the PR too, i'll make sure that gets an update
- can you remove the header "getting started"
- turn the paragraphs it into a numbered list

I imagine the section could be a paragraph and a few numbered bullets with the code sample, something like this:

> VScode has intellisense which the CSS Var Complete extension can tap into and pass a path to the node_modules folder when NPM's open-props is installed:
> 
> 1. In your VScode environment, navigate to the extensions marketplace, and install the CSS Var Complete extension.
> 2. Install Open Props from NPM
> 3. Add the NPM Open Props CSS file path to your .vscode/settings.json file, like this:
> 
> [great code example showing path to node_modules]

**Comment by Caleb335** [comment]
Awesome! Thank you for the feedback.

I'll start working on them.

**Comment by Caleb335** [comment]
Hi @argyleink, I made the changes you requested. Kindly take a look

**Review by argyleink — APPROVED** [review]
rad, thanks for kicking this all off and doing the research!

**Comment by Caleb335** [comment]
> rad, thanks for kicking this all off and doing the research!

Hi @argyleink,

Would it be nice if the autocomplete docs also contains the process of setting it up for other IDEs like atom, Sublime etc.

I can start making my research if you permit me.

**Comment by argyleink** [comment]
sounds great! helping folks get it setup in Atom and Sublime would def be nice 🙂 
thanks for offering more help!

**Comment by Caleb335** [comment]
> sounds great! helping folks get it setup in Atom and Sublime would def be nice 🙂 thanks for offering more help!

Anytime! 😎

**Comment by Caleb335** [comment]
I've started my research about autocomplete in atom, and I've found a use-case already.

Hopefully,  I'll send a PR by the end of the week.

**Pull request merged**
