### PR TITLE
great framework, shitty html

### PR DESCRIPTION
**Pull request by geomydas**

### CODE REVIEW

**Comment by aspizu** [comment]
looks like you just ran a formatter? whats the point of this PR?

**Comment by geomydas** [comment]
i ran a formatter and fixed some issues in the HTML. it skipped some heading levels and some other accesibility issues like using dl and dt instead of ul and li, using 2 h1s instead of just a span and etc. i don't know about the css tho

**Comment by argyleink** [comment]
reasonable goal, shitty title 😅 

the PR is way too much to review and the issues it solves aren't fully enumerated. sounds like issues should be opened up per problem you wish to solve, with smaller PRs fixing them. did you review everything the formatter did, or expect us to do it? 

typically, running a formatter on a project and calling their code shitty but now better, is a terrible way of contributing.

**Comment by geomydas** [comment]
> reasonable goal, shitty title 😅
> 
> the PR is way too much to review and the issues it solves aren't fully enumerated. sounds like issues should be opened up per problem you wish to solve, with smaller PRs fixing them. did you review everything the formatter did, or expect us to do it?
> 
> typically, running a formatter on a project and calling their code shitty but now better, is a terrible way of contributing.

will make a pull request more formalized lol

**Pull request closed without merging**
